const EVENTS = {
  connection: "connection",
  CLIENT: {
    LOGIN_USER: "LOGIN_USER",
    CREATE_ROOM: "CREATE_ROOM",
    SEND_ROOM_MESSAGE: "SEND_ROOM_MESSAGE",
    JOIN_ROOM: "JOIN_ROOM",
    RESET_ROOM: "RESET_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
  },
  SERVER: {
    ROOMS: "ROOMS",
    JOINED_ROOM: "JOINED_ROOM",
    ROOMS_MESSAGE: "ROOMS_MESSAGE",
    WELCOME_MESSAGE: "WELCOME_MESSAGE",
    RESET_ROOM: "RESET_ROOM",
    BYE_MESSAGE: "BYE_MESSAGE",
  },
};

export default EVENTS;
